"""Add reports observations and health metrics tables

Revision ID: 2e594cf604c2
Revises: 
Create Date: 2026-01-30 18:55:59.282872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e594cf604c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=False),
    sa.Column('contributions', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_metrics_computed_at'), 'health_metrics', ['computed_at'], unique=False)
    op.create_index(op.f('ix_health_metrics_metric_type'), 'health_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_health_metrics_user_id'), 'health_metrics', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'EXTRACTING', 'EXTRACTED', 'PROCESSING', 'PROCESSED', 'FAILED', 'CONFIRMED', name='reportstatus'), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('observation_type', sa.Enum('LAB_VALUE', 'VITAL_SIGN', 'PHYSICAL_MEASUREMENT', 'LIFESTYLE', 'SYMPTOM', name='observationtype'), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reference_min', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('reference_max', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_is_abnormal'), 'observations', ['is_abnormal'], unique=False)
    op.create_index(op.f('ix_observations_metric_name'), 'observations', ['metric_name'], unique=False)
    op.create_index(op.f('ix_observations_observation_type'), 'observations', ['observation_type'], unique=False)
    op.create_index(op.f('ix_observations_observed_at'), 'observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_observations_report_id'), 'observations', ['report_id'], unique=False)
    op.create_index(op.f('ix_observations_user_id'), 'observations', ['user_id'], unique=False)
    op.drop_table('playing_with_neon')
    op.add_column('chat_messages', sa.Column('message_metadata', sa.JSON(), nullable=True))
    op.add_column('chat_sessions', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('chat_sessions', 'last_active_at')
    op.drop_column('chat_messages', 'message_metadata')
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.drop_index(op.f('ix_observations_user_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_report_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_observed_at'), table_name='observations')
    op.drop_index(op.f('ix_observations_observation_type'), table_name='observations')
    op.drop_index(op.f('ix_observations_metric_name'), table_name='observations')
    op.drop_index(op.f('ix_observations_is_abnormal'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_health_metrics_user_id'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_metric_type'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_computed_at'), table_name='health_metrics')
    op.drop_table('health_metrics')
    # ### end Alembic commands ###
